### ISSUE TITLE
Avoid holes in the numbering of invoices

### ISSUE THREAD

**Issue by mayjo79** [libracore/erpnextswiss#82]
Hello,
Is your application capable of avoiding holes in the numbering of invoices?
I recently discovered ERPNext and it's a big problem because French law requires numbering invoices without holes.
This subject is often raised in ERPNext discussions but I did not find any satisfactory solution :
[https://github.com/frappe/erpnext/issues/8765](https://github.com/frappe/erpnext/issues/8765)
[https://discuss.erpnext.com/t/temporary-sales-invoice-number-before-submit/58570](https://discuss.erpnext.com/t/temporary-sales-invoice-number-before-submit/58570)

Thanks

**Comment by lasalesi** [comment]
The ERPNextSwiss application does not change the naming series behaviour of ERPNext.

I would also (as recommended in the link threads) recommend to disable permission to delete invoices. You can extend a draft to cancel function in order to push Drafts that are not to be used to cancelled state. Thereby you can maintain complete number series.

We have successfully applied this with several companies in Europe.

Technically, filling gaps with new documents can also be manually achieved (and theoretically also be automated) by changing the naming series offset.

I hope this is helpful, but will close this issue here as it is not an issue with ERPNextSwiss.
