### ISSUE TITLE
Pr in official repo

### ISSUE THREAD

**Issue by elbouillon** [libracore/erpnextswiss#88]
Hi, I'm new in erpnext and I've a new account online for our carpentry. 

To be able able to use this extension in the official repo, the extension needs to be approved by the dev team.

Are you planning to to send your modifications to the official openerp team ?

Thanks for your great job. By the way I'm interested to be involved for the Frenchmen translation

**Comment by lasalesi** [comment]
Hi,

thanks for your kind words. We are closely working together with the core team and are part of the ERPNext Foundation. Integration of ERPNextSwiss into the core has been discussed several times, e.g. 2019 at the ERPNext conference. Due to maintenance (e.g. the ISO 20022 module cannot be maintained by the core team), the responsiveness would be severely slowed down, which in business critical applications is not acceptable. Therefore, we have decided to keep it a separate app. This is still fully compatible and can be installed in any ERPNext installation.

You are of course always welcome to join to improve translations - or any other input is also welcome!
